global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eventhive'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']
        labels:
          app: 'eventhive'
          env: 'production'

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
