apiVersion: v1
kind: Service
metadata:
  name: eventhive-service
  labels:
    app: eventhive
spec:
  type: NodePort
  selector:
    app: eventhive
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30050
